apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  PRODUCT_DB_DSN: "root:password@tcp(ecommerce-db:8706)/ecommerce_product?parseTime=true"
  ORDER_DB_DSN: "root:password@tcp(ecommerce-db:8706)/ecommerce_order?parseTime=true"
  MYSQL_ROOT_PASSWORD: "password"
