appname = go-mvc
httpport = 8080
runmode = dev
copyrequestbody = true
jwt_secret = workpulse_super_secret_jwt_key_2026

[db]
host = 127.0.0.1
port = 3306
user = root
password = root
name = employee_db
